### ISSUE TITLE
Looks like Minetest 5.9.0 Released

### ISSUE THREAD

**Issue by lemonzest79** [ronoaldo/minetestclient#3]
Hiya again, Looks like Minetest 5.9.0 released, any chance of building the AppImage again, worked great last time on Fedora <3 thanks

https://github.com/minetest/minetest/releases/tag/5.9.0

**Comment by ronoaldo** [comment]
Thanks for the issue! I was trying to make some changes on how the minetest_game is fetched. Decided to go as the previous appimage and still bundle the game. I'll add a note to the release page informing that it is recommended to update the game from contentdb to use the recent features.

**Comment by ronoaldo** [comment]
Should be fixed in 6ce32d55a876b2d3622493cd8abd872d24b891a3 - waiting for CI to perform the release!

**Comment by ronoaldo** [comment]
https://github.com/ronoaldo/minetestclient/releases/tag/5.9.0-1

**Comment by lemonzest79** [comment]
Thanks :D
