### ISSUE TITLE
[Request] Minetest 5.9.1 Release

### ISSUE THREAD

**Issue by lemonzest79** [ronoaldo/minetestclient#4]
Hiya again

Seems Minetest has released a new update, could you please release a new AppImage?, and thanks for last time :)

https://github.com/minetest/minetest/releases/tag/5.9.1

**Comment by ronoaldo** [comment]
Thanks for rising this! Building the release, should be out soon, if my push made it properly trough CI 😓

**Comment by ronoaldo** [comment]
There we go! https://github.com/ronoaldo/minetestclient/releases/tag/5.9.1

**Comment by lemonzest79** [comment]
> There we go! https://github.com/ronoaldo/minetestclient/releases/tag/5.9.1

Thanks :D
