### ISSUE TITLE
5.10

### ISSUE THREAD

**Issue by Zughy** [ronoaldo/minetestclient#5]
(please!)

**Comment by lemonzest79** [comment]
seconded :) please <3

**Comment by ronoaldo** [comment]
@Zughy and @lemonzest79 do you think I should also rename the AppImage for 5.10 to Luanti? Just to keep inline with upstream.

Also, I'm still leaning towards shipping the Minetest Game by default with the AppImage.

**Comment by lemonzest79** [comment]
Yeah I think you should try to keep as upstream as possible with the name, is there any reason why you still ship the Minetest Game? when launching other versions it suggests downloading a game from the inbuilt store. Many thanks for packaging the AppImage :)

**Comment by ronoaldo** [comment]
> Yeah I think you should try to keep as upstream as possible with the name, is there any reason why you still ship the Minetest Game? when launching other versions it suggests downloading a game from the inbuilt store. Many thanks for packaging the AppImage :)

I was bundling the base game as I feelt like not having a game was not very practical. With the rename of the engine, it kind of makes more sense to drop that idea. Also, looks like the bundled game was not properly updating from ContentDB, so... it was actually even a bug.

Should be ready soon ... Waiting for the build to finish: https://github.com/ronoaldo/minetestclient/actions/runs/11946339538

- Used Luanti as the AppImiage artifacts and naming.
- Dropped Minetest Game from the bundle.

**Comment by ronoaldo** [comment]
Released! https://github.com/ronoaldo/minetestclient/releases/tag/5.10.0

**Comment by lemonzest79** [comment]
AppImage seems to run ok, connected to my personal Mineclonia server running native Luanti build 5.10 and everything seems fine, thanks :) <3

**Comment by ronoaldo** [comment]
Great, thanks for the feedback! The scripts should also still be able to produce older versions of Minetest and from now on support future builds for Luanti.
